name: Build and Analyze
on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: "tests${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  test-results-check-name: Test results

jobs:
  unit-tests-run:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Switch Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Collect Workflow Telemetry
        uses: AlexPerathoner/workflow-telemetry-action@v0.9
        with:
          metric_frequency_thousands_of_second: 100
      - name: get-pid
        run: |
          # loop
          for i in {1..1500}
          do
            id=$(pgrep -f workflow-telemetry-action)
            echo $id
            ps -p $id -o %cpu=,%mem= >> telemetry.txt
            sleep 1
          done
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: telemetry
          path: telemetry.txt


          
